using Bunzl.Core.Domain.DTOs.DevExpress;
using Bunzl.Domain.Commands.Fornecedor.Adicionar;
using Bunzl.Domain.Commands.Fornecedor.AdicionarAnexoProduto;
using Bunzl.Domain.Commands.Fornecedor.AdicionarDocumento;
using Bunzl.Domain.Commands.Fornecedor.AdicionarObservacao;
using Bunzl.Domain.Commands.Fornecedor.AdicionarPlanilhaCadastroProduto;
using Bunzl.Domain.Commands.Fornecedor.AdicionarPlanilhaCadastroProdutoBunzl;
using Bunzl.Domain.Commands.Fornecedor.AdicionarPlanilhaTabelaPreco;
using Bunzl.Domain.Commands.Fornecedor.AdicionarProduto;
using Bunzl.Domain.Commands.Fornecedor.Ativar;
using Bunzl.Domain.Commands.Fornecedor.Atualizar;
using Bunzl.Domain.Commands.Fornecedor.AtualizarProduto;
using Bunzl.Domain.Commands.Fornecedor.DeletarAnexoProduto;
using Bunzl.Domain.Commands.Fornecedor.DeletarDocumento;
using Bunzl.Domain.Commands.Fornecedor.DeletarObservacao;
using Bunzl.Domain.Commands.Fornecedor.DeletarProduto;
using Bunzl.Domain.Commands.Fornecedor.Inativar;
using Bunzl.Domain.Commands.Fornecedor.InvalidarPortal;
using Bunzl.Domain.Commands.Fornecedor.Listar;
using Bunzl.Domain.Commands.Fornecedor.ListarAnexosProduto;
using Bunzl.Domain.Commands.Fornecedor.ListarDocumentos;
using Bunzl.Domain.Commands.Fornecedor.ListarObservacoes;
using Bunzl.Domain.Commands.Fornecedor.ListarProdutos;
using Bunzl.Domain.Commands.Fornecedor.Obter;
using Bunzl.Domain.Commands.Fornecedor.ObterAnexoProduto;
using Bunzl.Domain.Commands.Fornecedor.ObterDocumento;
using Bunzl.Domain.Commands.Fornecedor.ObterPlanilhaCadastroProduto;
using Bunzl.Domain.Commands.Fornecedor.ObterProduto;
using Bunzl.Infra.CrossCutting.MediatoR.DTOs;
using Bunzl.Domain.Commands.Fornecedor.ListarHomologadoComTabelaPreco;
using Bunzl.Domain.Commands.Fornecedor.ListarProdutosHomologado;
using Bunzl.Domain.Commands.Fornecedor.ObterPlanilhaCadastroProdutoBunzl;
using Bunzl.Domain.Commands.Fornecedor.ObterPlanilhaTabelaPreco;

namespace Bunzl.Application.Interfaces;

public interface IFornecedorAppService
{
    Task<CommandResponse<DataSourcePageResponse>> ListarFornecedor(FornecedorListarRequest request);
    Task<CommandResponse<DataSourcePageResponse>> ListarFornecedorDocumentos(FornecedorListarDocumentosRequest request);
    Task<CommandResponse<FornecedorAdicionarResponse>> Adicionar(FornecedorAdicionarRequest request);
    Task<CommandResponse<FornecedorAdicionarDocumentoResponse>> AdicionarDocumento(FornecedorAdicionarDocumentoRequest request);
    Task<CommandResponse<FornecedorDeletarDocumentoResponse>> DeletarDocumento(Guid id, Guid documentoId);
    Task<CommandResponse<FornecedorAtualizarResponse>> AtualizarFornecedor(FornecedorAtualizarRequest request);
    Task<CommandResponse<FornecedorObterResponse>> Obter(FornecedorObterRequest request);
    Task<CommandResponse<FornecedorObterDocumentoResponse>> ObterDocumento(FornecedorObterDocumentoRequest request);
    Task<CommandResponse<FornecedorAdicionarObservacaoResponse>> AdicionarObservacao(FornecedorAdicionarObservacaoRequest request);
    Task<CommandResponse<DataSourcePageResponse>> ListarObservacoes(FornecedorListarObservacoesRequest request);
    Task<CommandResponse<FornecedorDeletarObservacaoResponse>> DeletarObservacao(FornecedorDeletarObservacaoRequest request);
    Task<CommandResponse<FornecedorAtivarResponse>> AtivarFornecedor(Guid id);
    Task<CommandResponse<FornecedorInativarResponse>> InativarFornecedor(Guid id);
    Task<CommandResponse<FornecedorInvalidarPortalResponse>> InvalidarPortalFornecedor(Guid id);
    Task<CommandResponse<ProdutosAdicionarPlanilhaResponse>> AdicionarPlanilhaProduto(ProdutosAdicionarPlanilhaRequest request);
    Task<CommandResponse<ProdutosObterPlanilhaResponse>> ObterPlanilhaProduto();
    Task<CommandResponse<ProdutosObterPlanilhaBunzlResponse>> ObterPlanilhaProdutoBunzl(ProdutosObterPlanilhaBunzlRequest request);
    Task<CommandResponse<ProdutosAdicionarPlanilhaBunzlResponse>> AdicionarPlanilhaProdutoBunzl(ProdutosAdicionarPlanilhaBunzlRequest request);
    Task<CommandResponse<ProdutosObterPlanilhaTabelaPrecoResponse>> ObterPlanilhaTabelaPreco(ProdutosObterPlanilhaTabelaPrecoRequest request);
    Task<CommandResponse<DataSourcePageResponse>> AdicionarPlanilhaTabelaPreco(ProdutosAdicionarPlanilhaTabelaPrecoRequest request);
    Task<CommandResponse<FornecedorProdutoAdicionarResponse>> AdicionarProduto(FornecedorProdutoAdicionarRequest request);
    Task<CommandResponse<FornecedorProdutoAtualizarResponse>> AtualizarProduto(FornecedorProdutoAtualizarRequest request);
    Task<CommandResponse<FornecedorProdutoDeletarResponse>> DeletarProduto(FornecedorProdutoDeletarRequest request);
    Task<CommandResponse<DataSourcePageResponse>> ListarFornecedorProdutos(FornecedorProdutoListarRequest fornecedorListarProdutosDevExpressRequest);
	Task<CommandResponse<DataSourcePageResponse>> ListarFornecedorProdutosHomologado(FornecedorProdutoListarHomologadoRequest request);
    Task<CommandResponse<DataSourcePageResponse>> ListarFornecedorHomologadoComTabelaPreco(FornecedorListarHomologadoComTabelaPrecoRequest request);
    Task<CommandResponse<FornecedorProdutoAdicionarAnexoResponse>> AdicionarProdutoAnexo(FornecedorProdutoAdicionarAnexoRequest request);
    Task<CommandResponse<FornecedorProdutoDeletarAnexoResponse>> DeletarProdutoAnexo(FornecedorProdutoDeletarAnexoRequest request);
    Task<CommandResponse<DataSourcePageResponse>> ListarFornecedorProdutoAnexos(FornecedorProdutoListarAnexoRequest request);
    Task<CommandResponse<FornecedorProdutoObterAnexoResponse>> ObterFornecedorProdutoAnexo(FornecedorProdutoObterAnexoRequest request);
    Task<CommandResponse<FornecedorObterProdutoResponse>> ObterProduto(FornecedorObterProdutoRequest request);
}