// <auto-generated />
using System;
using Bunzl.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bunzl.Infra.Data.Migrations
{
    [DbContext(typeof(BunzlContext))]
    [Migration("20241211165922_AjustesCasaDecimaisNegociacaoComercial")]
    partial class AjustesCasaDecimaisNegociacaoComercial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bunzl.Domain.Entities.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntidadeNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoAuditoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Auditoria", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DataUltimaAtualizacaoOrdemDeCompra")
                        .HasColumnType("timestamptz");

                    b.Property<string>("EmpresaBunzlId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("FlagRegravarTabelaPrecoErp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SiglaEmpresa")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Empresa", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CapacidadeProducaoFabricas")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoERP")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoFornecedor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoTabelaPreco")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Contato")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFabricaAuditada")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmpresaOfereceExclusividadeProdutosRegioes")
                        .HasColumnType("text");

                    b.Property<string>("EmpresaPossuiCertificacaoFabricas")
                        .HasColumnType("text");

                    b.Property<string>("EmpresaPossuiClientesNoBrasilQuemSao")
                        .HasColumnType("text");

                    b.Property<string>("EmpresaPossuiLaboratoriosPropriosParaPesquisaDesenvolvimento")
                        .HasColumnType("text");

                    b.Property<string>("EstadoProvincia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FabricasAuditadas")
                        .HasColumnType("text");

                    b.Property<string>("FazemOEM")
                        .HasColumnType("text");

                    b.Property<bool>("FlagAtivo")
                        .HasColumnType("boolean");

                    b.Property<bool>("FlagBloqueadoErp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("FlagFabricaAuditadaBunzl")
                        .HasColumnType("boolean");

                    b.Property<bool>("FlagJaEhParceiroBunzl")
                        .HasColumnType("boolean");

                    b.Property<bool>("FlagVeioDoERP")
                        .HasColumnType("boolean");

                    b.Property<string>("InformacoesGerais")
                        .HasColumnType("text");

                    b.Property<string>("InformacoesMercados")
                        .HasColumnType("text");

                    b.Property<string>("InformacoesPoliticas")
                        .HasColumnType("text");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("MoedaId")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NumeroIdentificacaoFiscal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PorcentagemVendasMercadosRepresentam")
                        .HasColumnType("text");

                    b.Property<string>("PossuemLaboratorioProprio")
                        .HasColumnType("text");

                    b.Property<string>("PrincipaisClientesSegmentosAtendidosEmpresa")
                        .HasColumnType("text");

                    b.Property<string>("QuaisMercadosEmpresaOpera")
                        .HasColumnType("text");

                    b.Property<string>("QuaisProdutosMaisVendidos")
                        .HasColumnType("text");

                    b.Property<string>("QuaisProdutosTercerizam")
                        .HasColumnType("text");

                    b.Property<string>("QuaisTermosPagamentosOferecidos")
                        .HasColumnType("text");

                    b.Property<string>("QuaisTiposProdutosFabricam")
                        .HasColumnType("text");

                    b.Property<string>("QuantidadeAnosEmpresaMercado")
                        .HasColumnType("text");

                    b.Property<string>("QuantidadeTrabalhadoresEmpresaPossui")
                        .HasColumnType("text");

                    b.Property<string>("QuantidadeTurnosTrabalhoRealizados")
                        .HasColumnType("text");

                    b.Property<string>("QuantidadeUnidadesFabricacaoOndeEstaoLocalizadas")
                        .HasColumnType("text");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ReceitaAnualEmpresa")
                        .HasColumnType("text");

                    b.Property<string>("SiglaFornecedor")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TelefoneArea")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("WhatsAppWechat")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("WhatsAppWechatArea")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.HasKey("Id");

                    b.HasIndex("MoedaId");

                    b.ToTable("Fornecedor", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.FornecedorDadoBancario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("FornecedorId");

                    b.Property<string>("Agencia")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EstadoProvincia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Iban")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeBanco")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NomeBeneficiario")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NumeroBanco")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("NumeroContaCorrente")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Pais")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Swift")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.HasKey("Id");

                    b.ToTable("FornecedorDadoBancario", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.FornecedorDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.ToTable("FornecedorDocumento", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.FornecedorObservacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.ToTable("FornecedorObservacao", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.FornecedorProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(18,5)");

                    b.Property<string>("AplicacoesPrincipais")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("CBM")
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("CapacidadeMensalFabrica")
                        .HasColumnType("decimal(18,5)");

                    b.Property<string>("CodigoArtigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoFornecedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoNCM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoSku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Composicao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Comprimento")
                        .HasColumnType("decimal(18,5)");

                    b.Property<string>("Cor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CorBunzl")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("CustoDesenvolvimentoEmbalagem")
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("CustoDetalhadoCombustivel")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("CustoDetalhadoEmbalagem")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("CustoDetalhadoEnergia")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("CustoDetalhadoMaoDeObra")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("CustoDetalhadoMateriaPrima")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("CustoDetalhadoTransporte")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("CustoRotulagemEmbalagem")
                        .HasColumnType("decimal(18,5)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoCompletaBunzl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DescricaoCompletaFornecedor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DetalhesEmbalagem")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Familia")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IncotermId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Largura")
                        .HasColumnType("decimal(18,5)");

                    b.Property<string>("NomeFabrica")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("PesoBruto")
                        .HasColumnType("decimal(18,5)");

                    b.Property<string>("PortoEmbarque")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int?>("QuantidadeCarregamentoContainer20Ft")
                        .HasColumnType("int");

                    b.Property<int?>("QuantidadeCarregamentoContainer40Ft")
                        .HasColumnType("int");

                    b.Property<int?>("QuantidadeCarregamentoContainer40Hc")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeMinimaPedido")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadePorCaixaMaster")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadePorEmbalagemInterna")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tamanho")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TamanhoBunzl")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("TempoEntrega")
                        .HasColumnType("integer");

                    b.Property<string>("TermoPagamento")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("TipoCaixaMaster")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoEmbalagemInterna")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UnidadeMedidaBunzl")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UnidadeMedidaCapacidadeMensal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UnidadeMedidaFornecedorMOQ")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UnidadeMedidaFornecedorPreco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("IncotermId");

                    b.ToTable("FornecedorProduto", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.FornecedorProdutoAnexo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FornecedorProdutoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorProdutoId");

                    b.ToTable("FornecedorProdutoAnexo", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.Incoterm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Incoterm", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.Moeda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Moeda", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.NegociacaoComercial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CampoAtuacao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("Codigo")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TermosPagamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Titulo")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.ToTable("NegociacaoComercial", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.NegociacaoComercialAnexo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NegociacaoComercialId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NegociacaoComercialId");

                    b.ToTable("NegociacaoComercialAnexo", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.NegociacaoComercialObservacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NegociacaoComercialId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NegociacaoComercialId");

                    b.ToTable("NegociacaoComercialObservacao", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.NegociacaoComercialProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("NegociacaoComercialId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacao")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,5)");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ValorSugerido")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("NegociacaoComercialId");

                    b.ToTable("NegociacaoComercialProduto", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.OrdemDeCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcordoFornecimento")
                        .HasColumnType("text");

                    b.Property<string>("BairroEnderecoImportador")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CnpjImportador")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoErpFornecedor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoEstabelecimento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoFabricante")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoFornecedor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ComplementoEnderecoImportador")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContatoFornecedor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContatoImportador")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataExp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataOrdem")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataRevisao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Desconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Destino")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmailFornecedor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmailImportador")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("EnderecoFabricante")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EnderecoFornecedor")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EnderecoImportador")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EstadoProvinciaImportador")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Frete")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ModoEntrega")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NomeAgente")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeComprador")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeFabricante")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeFornecedor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeImportador")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeVendedor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("NumeroContainer20")
                        .HasColumnType("integer");

                    b.Property<int?>("NumeroContainer40")
                        .HasColumnType("integer");

                    b.Property<int?>("NumeroContainer40HC")
                        .HasColumnType("integer");

                    b.Property<int?>("NumeroContainerOutros")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroEnderecoFornecedor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NumeroEnderecoImportador")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NumeroOrdem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroRevisao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("OutrasDespesas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaisImportador")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("PesoTotal")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("PrazoPagamento")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TaxaEmbalagem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TaxaInterna")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoFrete")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("TotalCBM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ValorTotal")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("ZipCodeImportador")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.ToTable("OrdemCompra", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.OrdemDeCompraAnexo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OrdemDeCompraId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrdemDeCompraId");

                    b.ToTable("OrdemCompraAnexo", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.OrdemDeCompraObservacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrdemDeCompraId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrdemDeCompraId");

                    b.ToTable("OrdemCompraObservacao", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.OrdemDeCompraProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoItem")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoNCM")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoSKU")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEstimadaPartida")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Etd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MoedaSigla")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NumeroLote")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("OrdemDeCompraId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrdemItem")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PosicaoItem")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("Quantidade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnidadeMedida")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ValorTotal")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("ValorUnitario")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("OrdemDeCompraId");

                    b.ToTable("OrdemCompraProduto", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.OrdemDeCompraUnidadeMedida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrdemDeCompraId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("QuantidadeTotal")
                        .IsRequired()
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrdemDeCompraId");

                    b.ToTable("OrdemCompraUnidadeMedida", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.TabelaPreco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoERP")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataFimVigencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicioVigencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("FlagExpirada")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("FornecedorId");

                    b.ToTable("TabelaPreco", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.TabelaPrecoProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("NovoPreco")
                        .HasColumnType("decimal(18,5)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TabelaPrecoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UltimoPrecoPraticado")
                        .HasColumnType("decimal(18,5)");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("TabelaPrecoId");

                    b.ToTable("TabelaPrecoProduto", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Area")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<Guid?>("ChaveCadastro")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChaveResetSenha")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoOtp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataChaveResetSenha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataGeracaoCodigoOtp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPrimeiroLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("FlagAtivo")
                        .HasColumnType("boolean");

                    b.Property<bool>("FlagVeioDoERP")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("PerfilPermissao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioAlteracao")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioCriacao")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Fornecedor_x_Empresa", b =>
                {
                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("FornecedorId");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("EmpresaId");

                    b.HasKey("FornecedorId", "EmpresaId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Fornecedor_x_Empresa");
                });

            modelBuilder.Entity("Usuario_x_Empresa", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("EmpresaId");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("UsuarioId");

                    b.HasKey("EmpresaId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Usuario_x_Empresa", (string)null);
                });

            modelBuilder.Entity("Usuario_x_Fornecedor", b =>
                {
                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("FornecedorId");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("UsuarioId");

                    b.HasKey("FornecedorId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Usuario_x_Fornecedor", (string)null);
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.Fornecedor", b =>
                {
                    b.HasOne("Bunzl.Domain.Entities.Moeda", "Moeda")
                        .WithMany()
                        .HasForeignKey("MoedaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moeda");
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.FornecedorDadoBancario", b =>
                {
                    b.HasOne("Bunzl.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithOne("FornecedorDadoBancario")
                        .HasForeignKey("Bunzl.Domain.Entities.FornecedorDadoBancario", "Id");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.FornecedorDocumento", b =>
                {
                    b.HasOne("Bunzl.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany("FornecedorDocumentos")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.FornecedorObservacao", b =>
                {
                    b.HasOne("Bunzl.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany("FornecedorObservacoes")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.FornecedorProduto", b =>
                {
                    b.HasOne("Bunzl.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany("FornecedorProdutos")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bunzl.Domain.Entities.Incoterm", "Incoterm")
                        .WithMany()
                        .HasForeignKey("IncotermId");

                    b.Navigation("Fornecedor");

                    b.Navigation("Incoterm");
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.FornecedorProdutoAnexo", b =>
                {
                    b.HasOne("Bunzl.Domain.Entities.FornecedorProduto", "FornecedorProduto")
                        .WithMany("FornecedorProdutoAnexos")
                        .HasForeignKey("FornecedorProdutoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("FornecedorProduto");
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.NegociacaoComercial", b =>
                {
                    b.HasOne("Bunzl.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.NegociacaoComercialAnexo", b =>
                {
                    b.HasOne("Bunzl.Domain.Entities.NegociacaoComercial", "NegociacaoComercial")
                        .WithMany("Anexos")
                        .HasForeignKey("NegociacaoComercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NegociacaoComercial");
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.NegociacaoComercialObservacao", b =>
                {
                    b.HasOne("Bunzl.Domain.Entities.NegociacaoComercial", "NegociacaoComercial")
                        .WithMany("NegociacaoComercialObservacoes")
                        .HasForeignKey("NegociacaoComercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NegociacaoComercial");
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.NegociacaoComercialProduto", b =>
                {
                    b.HasOne("Bunzl.Domain.Entities.NegociacaoComercial", "NegociacaoComercial")
                        .WithMany("Produtos")
                        .HasForeignKey("NegociacaoComercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NegociacaoComercial");
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.OrdemDeCompra", b =>
                {
                    b.HasOne("Bunzl.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.OrdemDeCompraAnexo", b =>
                {
                    b.HasOne("Bunzl.Domain.Entities.OrdemDeCompra", "OrdemDeCompra")
                        .WithMany("Anexos")
                        .HasForeignKey("OrdemDeCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemDeCompra");
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.OrdemDeCompraObservacao", b =>
                {
                    b.HasOne("Bunzl.Domain.Entities.OrdemDeCompra", "OrdemDeCompra")
                        .WithMany("Observacoes")
                        .HasForeignKey("OrdemDeCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemDeCompra");
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.OrdemDeCompraProduto", b =>
                {
                    b.HasOne("Bunzl.Domain.Entities.OrdemDeCompra", "OrdemDeCompra")
                        .WithMany("Produtos")
                        .HasForeignKey("OrdemDeCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemDeCompra");
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.OrdemDeCompraUnidadeMedida", b =>
                {
                    b.HasOne("Bunzl.Domain.Entities.OrdemDeCompra", "OrdemDeCompra")
                        .WithMany("UnidadesMedida")
                        .HasForeignKey("OrdemDeCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemDeCompra");
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.TabelaPreco", b =>
                {
                    b.HasOne("Bunzl.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bunzl.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany("TabelasPreco")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Empresa");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.TabelaPrecoProduto", b =>
                {
                    b.HasOne("Bunzl.Domain.Entities.FornecedorProduto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bunzl.Domain.Entities.TabelaPreco", "TabelaPreco")
                        .WithMany("Produtos")
                        .HasForeignKey("TabelaPrecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("TabelaPreco");
                });

            modelBuilder.Entity("Fornecedor_x_Empresa", b =>
                {
                    b.HasOne("Bunzl.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bunzl.Domain.Entities.Fornecedor", null)
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Usuario_x_Empresa", b =>
                {
                    b.HasOne("Bunzl.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_x_Empresa_EmpresaId");

                    b.HasOne("Bunzl.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_x_Empresa_UsuarioId");
                });

            modelBuilder.Entity("Usuario_x_Fornecedor", b =>
                {
                    b.HasOne("Bunzl.Domain.Entities.Fornecedor", null)
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_x_Fornecedor_FornecedorId");

                    b.HasOne("Bunzl.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_x_Fornecedor_UsuarioId");
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.Fornecedor", b =>
                {
                    b.Navigation("FornecedorDadoBancario");

                    b.Navigation("FornecedorDocumentos");

                    b.Navigation("FornecedorObservacoes");

                    b.Navigation("FornecedorProdutos");

                    b.Navigation("TabelasPreco");
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.FornecedorProduto", b =>
                {
                    b.Navigation("FornecedorProdutoAnexos");
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.NegociacaoComercial", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("NegociacaoComercialObservacoes");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.OrdemDeCompra", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("Observacoes");

                    b.Navigation("Produtos");

                    b.Navigation("UnidadesMedida");
                });

            modelBuilder.Entity("Bunzl.Domain.Entities.TabelaPreco", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
